version: 2
jobs:
  test:
    docker:
      - image: circleci/golang:1.12
    working_directory: /go/src/github.com/craigfurman/networkmanager-vpn-web-ui
    steps:
      - checkout
      - run: make test

workflows:
  version: 2
  pipeline:
    jobs:
      - test
