version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.10.1
    working_directory: /go/src/github.com/craigfurman/networkmanager-vpn-web-ui
    steps:
      - checkout
      - run: make test
